version: '3'
services:
  web:
    build: .
    container_name: flask_blog_dc
    image: flask_web_img
    ports: 
     - "3000:5000"
    
    depends_on:
     [pg_database]
    restart: always

  pg_database:
   image: postgres:15
   container_name: flask_pg_db_dc
   ports:
      - "5432:5432"
   volumes:
      - flask_web_db:/var/lib/postgresql/data

    # define environments for the postgres
   environment:
      - POSTGRES_PASSWORD=_BadriPostgres1@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flask_blogs
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
 flask_web_db:      